// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fOYQPOOOOQO'#C_'#C_O!sQPO'#C^QYQPOOO#OQPO'#CaO#TQQO'#CbO#TQQO'#CcOOQO'#C`'#C`OOQO'#Cd'#CdO#YQPO,58xOOQO'#Cf'#CfQYQPOOOOQO,58{,58{OOQO'#Ce'#CeO%PQQO,58|O&yQQO,58}OOQO-E6b-E6bOOQO-E6d-E6dOOQO-E6c-E6c",
  stateData: "(s~O]OS^OS~O_PO`POaPObPOcPOdPOePOfPOgPOhPOiPOjPOkPOlPOmPOnPOoPOpPOqPOrPOsPOtPOuPO~OvSOxTOzUO~Ow[O~Oy]O~OvSOxTOzUOZQa_Qa`QaaQabQacQadQaeQafQagQahQaiQajQakQalQamQanQaoQapQaqQarQasQatQauQa~Oy]OZUa_Ua`UaaUabUacUadUaeUafUagUahUaiUajUakUalUamUanUaoUapUaqUarUasUatUauUavUaxUazUa~Oy]OZVa_Va`VaaVabVacVadVaeVafVagVahVaiVajVakValVamVanVaoVapVaqVarVasVatVauVavVaxVazVa~O",
  goto: "!WZPP[chlllpv!QQROTYRZVQORZTWQXTVQXQXQR`XQ^TQ_UTb^_QZRRaZ",
  nodeNames: "⚠ Program Statement Command Arg Register Number Operand",
  maxTerm: 42,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ",z~RfXY!gYZ!gpq!gst!ltu!q!Q!Y!v!Y![!}!]!^#S!c!d#k!d!e!}!e!f$^!f!g%e!g!i!}!l!m&p!n!o'R!o!p(W!p!q(i!q!r)Q!r!s)]!t!u*W!u!v*]#T#Z!}~!lO]~~!qOx~~!vOz~R!}OyQwPQ#SOyQ~#XS^~OY#SZ;'S#S;'S;=`#e<%lO#S~#hP;=`<%l#S~#pQyQ!f!g#v!p!q$R~#yP!f!g#|~$ROf~~$UP!f!g$X~$^Od~~$cQyQ!g!h$i!n!o%S~$lQ!q!r$r!t!u$}~$uP!v!w$x~$}Ok~~%SOj~~%VP!h!i%Y~%]P!|!}%`~%eOi~~%jPyQ!c!d%m~%pP!v!w%s~%vP!c!d%y~%|P!e!f&P~&SP!c!d&V~&YP!n!o&]~&`P!n!o&c~&hPs~!S!T&k~&pOt~~&sP!o!p&v~&yP!r!s&|~'ROb~~'UR!f!g'_!g!h'j!u!v'u~'bP!t!u'e~'jO_~~'mP!t!u'p~'uOo~~'xP!k!l'{~(OP!r!s(R~(WOr~~(ZP!c!d(^~(aP!z!{(d~(iOu~~(lP!q!r(o~(rP!q!r(u~(xP!r!s({~)QOm~~)TP!t!u)W~)]Oe~~)`P!t!u)c~)fP!g!h)i~)lP!u!v)o~)rP!g!h)u~)xP!p!q){~*OP!v!w*R~*WOc~~*]Ov~~*`T!g!h*o!u!v+Q!v!w+w!w!x,b!|!},u~*rP!q!r*u~*xP!v!w*{~+QOl~~+TQ!q!r+Z!x!y+f~+^P!r!s+a~+fOq~~+iP!q!r+l~+oP!r!s+r~+wOp~~+zP!t!u+}~,SP`~!r!s,V~,YP!e!f,]~,bOa~~,eP!d!e,h~,mPg~!x!y,p~,uOh~~,zOn~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
