// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fOVQPOOOOQO'#C_'#C_O!sQPO'#C^QVQPOOO$jQQO'#CbO$oQPO'#CcOOQO'#Ca'#CaO$tQPO'#C`OOQO,58x,58xOOQO'#Cf'#CfQVQPOOOOQO,58|,58|OOQO'#Cd'#CdO&kQPO,58}OOQO'#Ce'#CeO(eQPO,58zOOQO-E6d-E6dOOQO-E6b-E6bOOQO-E6c-E6c",
  stateData: "*[~O]OS~O^PO_PO`POaPObPOcPOdPOePOfPOgPOhPOiPOjPOkPOlPOmPOnPOoPOpPOqPOrPOsPOtPOuPO~OvSOxTOZQX^QX_QX`QXaQXbQXcQXdQXeQXfQXgQXhQXiQXjQXkQXlQXmQXnQXoQXpQXqQXrQXsQXtQXuQX~OwZO~Oy[O~OvSOxTOZSX^SX_SX`SXaSXbSXcSXdSXeSXfSXgSXhSXiSXjSXkSXlSXmSXnSXoSXpSXqSXrSXsSXtSXuSX~Oy[OZVa^Va_Va`VaaVabVacVadVaeVafVagVahVaiVajVakValVamVanVaoVapVaqVarVasVatVauVavVaxVa~OvSOxTOZSa^Sa_Sa`SaaSabSacSadSaeSafSagSahSaiSajSakSalSamSanSaoSapSaqSarSasSatSauSa~O",
  goto: "!ZZPP[chkrrw}!TQROTXRYVQORYRWQQVQT^V_VUQV_Q]TRa]Q_VRb_QYRR`Y",
  nodeNames: "⚠ Program Statement Command ArgList Arg Register Number",
  maxTerm: 41,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ",v~RdXY!aYZ!apq!a!Q!R!f!R!Y!u!Y![!|!c!d#R!d!e!|!e!f#t!f!g${!g!i!|!l!m&W!n!o&i!o!p'n!p!q(P!q!r(h!r!s(s!t!u)n!u!v)s#T#Z!|~!fO]~R!mPyPwQ#l#m!pP!uOxPR!|OyPwQP#ROyP~#WQyP!f!g#^!p!q#i~#aP!f!g#d~#iOd~~#lP!f!g#o~#tOb~~#yQyP!g!h$P!n!o$j~$SQ!q!r$Y!t!u$e~$]P!v!w$`~$eOi~~$jOh~~$mP!h!i$p~$sP!|!}$v~${Og~~%QPyP!c!d%T~%WP!v!w%Z~%^P!c!d%a~%dP!e!f%g~%jP!c!d%m~%pP!n!o%s~%vP!n!o%y~&OPq~!S!T&R~&WOr~~&ZP!o!p&^~&aP!r!s&d~&iO`~~&lR!f!g&u!g!h'Q!u!v']~&xP!t!u&{~'QO^~~'TP!t!u'W~']Om~~'`P!k!l'c~'fP!r!s'i~'nOp~~'qP!c!d't~'wP!z!{'z~(POs~~(SP!q!r(V~(YP!q!r(]~(`P!r!s(c~(hOk~~(kP!t!u(n~(sOc~~(vP!t!u(y~(|P!g!h)P~)SP!u!v)V~)YP!g!h)]~)`P!p!q)c~)fP!v!w)i~)nOa~~)sOv~~)vU!g!h*Y!t!u*k!u!v*|!v!w+s!w!x,^!|!},q~*]P!q!r*`~*cP!v!w*f~*kOj~~*nP!g!h*q~*tP!u!v*w~*|Ou~~+PQ!q!r+V!x!y+b~+YP!r!s+]~+bOo~~+eP!q!r+h~+kP!r!s+n~+sOn~~+vP!t!u+y~,OP_~!r!s,R~,UP!e!f,X~,^Ot~~,aP!d!e,d~,iPe~!x!y,l~,qOf~~,vOl~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
