// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  StatementOrDefinition = 2,
  Statement = 3,
  Command = 4,
  Arg = 5,
  Value = 6,
  Register = 7,
  Number = 8,
  Address = 9,
  AnyIdentifier = 10,
  NumberIdentifier = 11,
  Identifier = 12,
  AddressIdentifier = 13,
  Definition = 14,
  DefinitionValue = 15,
  Label = 16
