// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fOVQPOOOOQO'#C_'#C_OhQPO'#C^QVQPOOO!SQQO'#CbO!XQPO'#CcOOQO'#Ca'#CaO!^QPO'#C`OOQO,58x,58xOOQO'#Cf'#CfQVQPOOOOQO,58|,58|OOQO'#Cd'#CdO!xQPO,58}OOQO'#Ce'#CeO#gQPO,58zOOQO-E6d-E6dOOQO-E6b-E6bOOQO-E6c-E6c",
  stateData: "$R~O]OS~O^PO_PO`POaPObPO~OcSOeTOZQX^QX_QX`QXaQXbQX~OdZO~Of[O~OcSOeTOZSX^SX_SX`SXaSXbSX~Of[OZVa^Va_Va`VaaVabVacVaeVa~OcSOeTOZSa^Sa_Sa`SaaSabSa~O",
  goto: "!ZZPP[chkrrw}!TQROTXRYVQORYRWQQVQT^V_VUQV_Q]TRa]Q_VRb_QYRR`Y",
  nodeNames: "⚠ Program Statement Command ArgList Arg Register Number",
  maxTerm: 22,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "$n~R^XY}YZ}pq}!Q!R!S!R!Y!c!Y![!j!c!d!o!d!f!j!f!g#S!g!i!j!o!p#g!t!u$W!u!v$]#T#Z!j~!SO]~R!ZPfPdQ#l#m!^P!cOePR!jOfPdQP!oOfP~!tPfP!f!g!w~!zP!f!g!}~#SO_~~#XPfP!k!l#[~#_P!x!y#b~#gOb~~#jQ!q!r#p!w!x#{~#sP!x!y#v~#{O^~~$OP!n!o$R~$WOa~~$]Oc~~$`P!w!x$c~$fP!d!e$i~$nO`~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
